florapp/orders/urls.py
from django.urls import path

from . import views

app_name = "orders"
urlpatterns = [
    path("",views.IndexView.as_view(), name="index"),
    path("status/<str:status>/",views.IndexView.as_view(), name="index"),
    path("<int:pk>/",views.DetailView.as_view(), name="detail"),
    path("new/",views.CreateOrderView.as_view(), name="new"),
    path("prueba/",views.prueba, name="prueba"),
    path("product/",views.load_product, name="product")
]

florapp/users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    
]

florapp/orders/models.py
from django.db import models
from users.models import User

class Flower(models.Model):

    name = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    unit_price = models.FloatField()

    def __str__(self):
        return self.name

class Order(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    flower = models.ForeignKey(Flower,on_delete=models.PROTECT)
    units = models.IntegerField(default=0)
    observations_text = models.CharField(max_length=500)
    status = models.CharField(max_length=30, choices=[('Activo','Activo'),('Cancelado','Cancelado'),('Despachado','Despachado'),('Entregado','Entregado')], default='Activo')
    pub_date = models.DateTimeField("date published",auto_now_add=True)

    def __str__(self):
        return 'Orden ' + str(self.pk)

florapp/orders/forms.py
# django
from django import forms

# models

from orders.models import Flower, Order

class OrderForm(forms.ModelForm):
    """Order model form"""

    class Meta:
        """Form settings"""

        model = Order
        fields = ['user','flower','units', 'observations_text']

    flower = forms.ModelChoiceField(
        queryset = Flower.objects.all(), 
        empty_label = None,
    )

florapp/users/forms.py
import re
from django import forms
from users.models import User

class SignUpForm(forms.Form):

    first_name = forms.CharField(min_length= 2, max_length=15)
    last_name = forms.CharField(min_length= 2, max_length=15)
    username = forms.CharField(min_length= 4, max_length=15)
    email = forms.CharField(min_length=6,max_length=50,widget = forms.EmailInput())
    password = forms.CharField(max_length=70 , widget=forms.PasswordInput())
    password_confirmation = forms.CharField(max_length=70 , widget=forms.PasswordInput())

    def clean_username(self):
        """Username must be unique"""

        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('El username ya existe')
        pattern = "^[A-Za-z0-9_]*$"
        valid = bool(re.match(pattern, username))
        if not valid:
            raise forms.ValidationError("El username solo puede contener letras A-z, numeros 0-9 y _")
        return username

    def clean_email(self):
        """email must be unique"""

        email = self.cleaned_data['email']
        email_taken = User.objects.filter(email=email).exists()
        if email_taken:
            raise forms.ValidationError('El email ya esta registrado')
        return email

    def clean(self):
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Las contraseñas no coinciden')

        return data

    def save(self):
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        user.save()

florapp/orders/views.py
from multiprocessing import context
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy
from orders.models import Order
from orders.forms import OrderForm
from django.shortcuts import render



class IndexView(LoginRequiredMixin,generic.ListView):
    template_name = "orders/index2.html"
    context_object_name = "context"

    def get_queryset(self):
        """Return the last  published orders"""
        user = self.request.user
        context = {}
        context['latest_orders_list'] = Order.objects.filter(user=user)
        if 'status' in self.kwargs:
            status = self.kwargs['status']
            context[f'{status}'] = status
            context['latest_orders_list'] =Order.objects.filter(user=user).filter(status=status)
            return context
        context['todas'] = 'todas'
        return context

class DetailView(LoginRequiredMixin,generic.DetailView):
    model = Order
    template_name = "orders/detail.html"

    def get_queryset(self):
        user = self.request.user 
        return Order.objects.filter(user=user)

class CreateOrderView(LoginRequiredMixin, generic.CreateView):
    """Create new Order"""

    form_class = OrderForm
    success_url = reverse_lazy('orders:index')
    template_name = 'orders/new.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context

def load_index(request):
    return render(request,"orders/index.html")

def load_aboutus(request):
    return render(request,"orders/about-us.html")

def load_blog(request):
    return render(request,"orders/blog.html")

def load_cart(request):
    return render(request,"orders/cart.html")

def load_checkout(request):
    return render(request,"orders/checkout.html")

def load_compare(request):
    return render(request,"orders/compare.html")

def load_contactus(request):
    return render(request,"orders/contact-us.html")

def load_error_404(request, exception):
    return render(request,"orders/error-404.html",status=404)

def load_faq(request):
    return render(request,"orders/frequently-questions.html")

def load_login(request):
    return render(request,"orders/login.html")

def load_myaccount(request):
    return render(request,"orders/my-account.html")

def load_register(request):
    return render(request,"orders/register.html")

def load_shop(request):
    return render(request,"orders/shop.html")

def load_whislist(request):
    return render(request,"orders/error-404.html")

def load_product(request):
    return render(request,"orders/product-details.html")


def prueba(request):
    return render(request,"orders/prueba.html")

def prueba2(request):
    return render(request,"orders/prueba2.html")

florapp/orders/templates/orders/blog-details-fullwidth.html
{% extends 'orders/base.html' %}
{% load static %}

{% block container %}

<!-- Blog Area Wrapper Start Here -->
<div class="blog-area-wrapper">
    <!-- Breadcrumb Area Start Here -->
    <div class="breadcrumbs-area position-relative">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center">
                    <div class="breadcrumb-content position-relative section-content">
                        <h3 class="title-3">Blog Details Fullwidth</h3>
                        <ul>
                            <li><a href="{% url 'index' %}">Home</a></li>
                            <li>Blog</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Area End Here -->
    <!-- Blog Main Area Start Here -->
    <div class="blog-main-area">
        <div class="container container-default custom-area">
            <div class="row">
                <div class="col-12 col-custom widget-mt">
                    <!-- Blog Details wrapper Area Start -->
                    <div class="blog-post-details">
                        <figure class="blog-post-thumb mb-5">
                            <img src="{% static 'orders/assets/images/blog/blog1.jpg' %}" alt="Blog Image">
                        </figure>
                        <section class="blog-post-wrapper product-summery">
                            <div class="section-content section-title">
                                <h2 class="section-title-2 mb-3">Standard blog post one</h2>
                                <p class="mb-4">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage.</p>
                                <blockquote class="blockquote mb-4">
                                    <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock</p>
                                </blockquote>
                                <p class="mb-5">and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>
                            </div>
                            <div class="share-article">
                                <span class="left-side">
                            <a href="#"> <i class="fa fa-long-arrow-left"></i> Older Post</a>
                        </span>
                                <h6 class="text-uppercase">Share this article</h6>
                                <span class="right-side">
                        <a href="#">Newer Post <i class="fa fa-long-arrow-right"></i></a>
                        </span>
                            </div>
                            <div class="social-share">
                                <a href="#"><i class="fa fa-facebook-square facebook-color"></i></a>
                                <a href="#"><i class="fa fa-twitter-square twitter-color"></i></a>
                                <a href="#"><i class="fa fa-linkedin-square linkedin-color"></i></a>
                                <a href="#"><i class="fa fa-pinterest-square pinterest-color"></i></a>
                            </div>
                            <div class="comment-area-wrapper mt-5">
                                <div class="comments-view-area">
                                    <h3 class="mb-5">3 Comments</h3>
                                    <div class="single-comment-wrap mb-4 d-flex">
                                        <figure class="author-thumb">
                                            <a href="#">
                                                <img src="{% static 'orders/assets/images/review/1.jpg' %}" alt="Author">
                                            </a>
                                        </figure>
                                        <div class="comments-info">
                                            <p class="mb-2">This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet</p>
                                            <div class="comment-footer d-flex justify-content-between">
                                                <a href="#" class="author"><strong>Duy</strong> - July 30, 2021</a>
                                                <a href="#" class="btn-reply"><i class="fa fa-reply"></i> Reply</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="single-comment-wrap mb-4 comment-reply d-flex">
                                        <figure class="author-thumb">
                                            <a href="#">
                                                <img src="{% static 'orders/assets/images/review/1.jpg' %}" alt="Author">
                                            </a>
                                        </figure>
                                        <div class="comments-info">
                                            <p class="mb-2">Praesent bibendum risus pellentesque faucibus rhoncus. Etiam a mollis odio. Integer urna nisl, fermentum eu mollis et, gravida eu elit.</p>
                                            <div class="comment-footer d-flex justify-content-between">
                                                <a href="#" class="author"><strong>Jack</strong> - July 30, 2021</a> <a href="#" class="btn-reply"><i class="fa fa-reply"></i> Reply</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="single-comment-wrap mb-4 d-flex">
                                        <figure class="author-thumb">
                                            <a href="#">
                                                <img src="{% static 'orders/assets/images/review/1.jpg' %}" alt="Author">
                                            </a>
                                        </figure>
                                        <div class="comments-info">
                                            <p class="mb-2">Praesent bibendum risus pellentesque faucibus rhoncus. Etiam a mollis odio. Integer urna nisl, fermentum eu mollis et, gravida eu elit.</p>
                                            <div class="comment-footer d-flex justify-content-between">
                                                <a href="#" class="author"><strong>Duy</strong> - July 30, 2021</a>
                                                <a href="#" class="btn-reply"><i class="fa fa-reply"></i> Reply</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                    <!-- Blog Details Wrapper Area End -->
                    <!-- Blog Comments Area Start Here -->
                    <form action="#">
                        <div class="comment-box">
                            <h3>Leave A Comment</h3>
                            <div class="row">
                                <div class="col-12 col-custom">
                                    <div class="input-item mt-4 mb-4">
                                        <textarea cols="30" rows="5" name="comment" class="border rounded-0 w-100 custom-textarea input-area" placeholder="Message"></textarea>
                                    </div>
                                </div>
                                <div class="col-md-6 col-custom">
                                    <div class="input-item mb-4">
                                        <input class="border rounded-0 w-100 input-area name" type="text" placeholder="Name">
                                    </div>
                                </div>
                                <div class="col-md-6 col-custom">
                                    <div class="input-item mb-4">
                                        <input class="border rounded-0 w-100 input-area email" type="text" placeholder="Email">
                                    </div>
                                </div>
                                <div class="col-12 col-custom mt-40">
                                    <button type="submit" class="btn flosun-button primary-btn rounded-0 w-100">Post comment</button>
                                </div>
                            </div>
                        </div>
                    </form>
                    <!-- Blog Comments Area End Here -->
                </div>
            </div>
        </div>
    </div>
    <!-- Blog Main Area End Here -->
</div>
<!-- Blog Area Wrapper End Here -->

{% endblock container %}

{% block container2 %}
<!-- Scroll to Top Start -->
<a class="scroll-to-top" href="#">
    <i class="lnr lnr-arrow-up"></i>
</a>
<!-- Scroll to Top End -->
{% endblock  %}

florapp/orders/templates/orders/contact-us.html
{% extends 'orders/base.html' %}
{% load static %}
{% block container %}

<!-- Breadcrumb Area Start Here -->
<div class="breadcrumbs-area position-relative">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <div class="breadcrumb-content position-relative section-content">
                    <h3 class="title-3">Contact Us</h3>
                    <ul>
                        <li><a href="index.html">Home</a></li>
                        <li>Contact Us</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Area End Here -->
<!-- Contact Us Area Start Here -->
<div class="contact-us-area mt-no-text">
    <div class="container custom-area">
        <div class="row">
            <div class="col-lg-4 col-md-6 col-custom">
                <div class="contact-info-item">
                    <div class="con-info-icon">
                        <i class="lnr lnr-map-marker"></i>
                    </div>
                    <div class="con-info-txt">
                        <h4>Our Location</h4>
                        <p>(800) 123 456 789 / (800) 123 456 789 info@example.com</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-custom">
                <div class="contact-info-item">
                    <div class="con-info-icon">
                        <i class="lnr lnr-smartphone"></i>
                    </div>
                    <div class="con-info-txt">
                        <h4>Contact us Anytime</h4>
                        <p>Mobile: 012 345 678<br>Fax: 123 456 789</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-12 col-custom text-align-center">
                <div class="contact-info-item">
                    <div class="con-info-icon">
                        <i class="lnr lnr-envelope"></i>
                    </div>
                    <div class="con-info-txt">
                        <h4>Support Overall</h4>
                        <p>Support24/7@example.com <br> info@example.com</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-custom">
                <form method="post" action="{% static 'orders/assets/php/mail.php' %}" id="contact-form" accept-charset="UTF-8" class="contact-form">
                    <div class="comment-box mt-5">
                        <h5 class="text-uppercase">Get in Touch</h5>
                        <div class="row mt-3">
                            <div class="col-md-6 col-custom">
                                <div class="input-item mb-4">
                                    <input class="border-0 rounded-0 w-100 input-area name gray-bg" type="text" name="con_name" id="con_name" placeholder="Name">
                                </div>
                            </div>
                            <div class="col-md-6 col-custom">
                                <div class="input-item mb-4">
                                    <input class="border-0 rounded-0 w-100 input-area email gray-bg" type="email" name="con_email" id="con_email" placeholder="Email">
                                </div>
                            </div>
                            <div class="col-12 col-custom">
                                <div class="input-item mb-4">
                                    <input class="border-0 rounded-0 w-100 input-area email gray-bg" type="text" name="con_content" id="con_content" placeholder="Subject">
                                </div>
                            </div>
                            <div class="col-12 col-custom">
                                <div class="input-item mb-4">
                                    <textarea cols="30" rows="5" class="border-0 rounded-0 w-100 custom-textarea input-area gray-bg" name="con_message" id="con_message" placeholder="Message"></textarea>
                                </div>
                            </div>
                            <div class="col-12 col-custom mt-40">
                                <button type="submit" id="submit" name="submit" class="btn flosun-button secondary-btn theme-color rounded-0">Send A Message</button>
                            </div>
                            <p class="col-8 col-custom form-message mb-0"></p>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Contact Us Area End Here -->
{% endblock container %}

florapp/orders/templates/orders/detail.html
{% extends 'orders/base.html' %}
{% load static %}

{% block head_content %}
<title>Orden {{order.id}}</title>
{% endblock %}

{% block container %}
    <link rel="stylesheet" href="{% static 'orders/detail.css' %}">
  
    <header><h1> Orden #{{order.id}}</h1></header>

    {% if error_message %}
        <p><strong> {{ error_message }}</strong></p>
    {% endif %}
    <main>
        <fieldset class="detail">
            <p>Unidades: {{ order.units}}</p>
            <p>Flor: {{ order.flower.name}}</p>
            <p>Fecha de solicitud: {{ order.pub_date}}</p>
            <p>Observaciones:   {{ order.observations_text}} </p>
            <p>Estado:  {{ order.status}} </p>
            
        </fieldset>
        

    </main>
    
{% endblock%}

florapp/orders/templates/orders/error-404.html
{% extends 'orders/base.html' %}
{% load static %}

{% block container %}

<!-- Breadcrumb Area Start Here -->
<div class="breadcrumbs-area position-relative">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <div class="breadcrumb-content position-relative section-content">
                    <h3 class="title-3">Error 404</h3>
                    <ul>
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li>Error 404</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Area End Here -->
<!-- Error 404 Area Start Here -->
<div class="error-area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="error_form">
                    <h1>404</h1>
                    <h2>Opps! PAGE NOT BE FOUND</h2>
                    <p>Sorry but the page you are looking for does not exist, have been<br> removed, name changed or is temporarily unavailable.</p>
                    <form action="#">
                        <input placeholder="Search..." type="text">
                        <button type="submit"><i class="fa fa-search"></i></button>
                    </form>
                    <a href="{% url 'index' %}">Back to home page</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Error 404 Area End Here -->
{% endblock %}

florapp/orders/templates/orders/index2.html
{% extends 'orders/base.html' %}
{% load static %}

{% block head_content %}
<title>Listado de Ordenes</title>
{% endblock %}

{% block container %}
    <link rel="stylesheet" href="{% static 'orders/index.css' %}">
    <header><h1>Listado de Ordenes</h1></header>
    <nav class="nav_menu">
        <ul>
            <li>
                <a class="{{ context.todas }}" href="{% url 'orders:index' %}">Todas</a>
            </li>
            <li>
                <a class="{{ context.Activo }}" href="{% url 'orders:index' 'Activo' %}"> Activas</a>
            </li>
            <li>
                <a class="{{ context.Cancelado }}" href="{% url 'orders:index' 'Cancelado' %}">Canceladas</a>
            </li>
            <li>
                {% comment %} <a class="{{ context.Despachado }}" href="{% url 'orders:index' 'Despachado' %}">Despachadas</a> {% endcomment %}
            </li>
            <li>
                <a class="{{ context.Entregado }}" href="{% url 'orders:index' 'Entregado' %}">Entregadas</a>
            </li>
            
        </ul>
    </nav>
    <main>
        
        {% if context.latest_orders_list %}
        
            <ul class="ul_index">
            {% for order in context.latest_orders_list  %}
                <fieldset>
                    <li class="li_index">
                        <a href="{% url 'orders:detail' order.id %}">
                            Orden #{{ order.id }}<br>
                            <p>{{order.units}} unidades de {{order.flower.name}}</p>
                        </a>
                    </li>
                </fieldset>
            {% endfor %}
            </ul>
         
        {% else %}
            <p>No orders are available.</p>
        {% endif %}
    </main>
    
{% endblock%}

florapp/orders/templates/orders/register.html
{% extends 'orders/base.html' %}
{% load static %}

{% block container %}

<!-- Breadcrumb Area Start Here -->
<div class="breadcrumbs-area position-relative">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <div class="breadcrumb-content position-relative section-content">
                    <h3 class="title-3">Login-Register</h3>
                    <ul>
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li>Login-Register</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Area End Here -->
<!-- Register Area Start Here -->
<div class="login-register-area mt-no-text">
    <div class="container container-default-2 custom-area">
        <div class="row">
            <div class="col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-custom">
                <div class="login-register-wrapper">
                    <div class="section-content text-center mb-5">
                        <h2 class="title-4 mb-2">Create Account</h2>
                        <p class="desc-content">Please Register using account detail bellow.</p>
                        {% if form.errors %}
                            <div style="color:red">{{form.non_field_errors}}</div>
                        {%endif%}
                    </div>
                    <form action="{% url 'register' %}" method="post">
                        {% csrf_token %}
                        <div class="single-input-item mb-3">
                            <input type="text" name="first_name" placeholder="First Name" required="" id="id_first_name">
                        </div>
                        <div class="single-input-item mb-3">
                            <input type="text" name="last_name" placeholder="Last Name" required="" id="id_last_name">
                        </div>
                        <div class="single-input-item mb-3">
                            <div style="color:red">{{form.errors.username}}</div>
                            <input type="text" name="username" placeholder="Username" required="" id="id_username">
                        </div>
                        <div class="single-input-item mb-3">
                            <div style="color:red">{{form.errors.email}}</div>
                            <input type="email" name="email" placeholder="Email" required="" id="id_email">
                        </div>
                        <div class="single-input-item mb-3">
                            <div style="color:red">{{form.errors.password}}</div>
                            <input type="password" name="password" placeholder="Enter your Password" required="" id="id_password">
                        </div>
                        <div class="single-input-item mb-3">
                            <div style="color:red">{{form.errors.password_confirmation}}</div>
                            <input type="password" name="password_confirmation" placeholder="Confirm your Password" required="" id="id_password_confirmation">
                        </div>
                        <div class="single-input-item mb-3">
                            <div class="login-reg-form-meta d-flex align-items-center justify-content-between">
                                <div class="remember-meta mb-3">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="rememberMe">
                                        <label class="custom-control-label" for="rememberMe">Subscribe Our Newsletter</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="single-input-item mb-3">
                            <button class="btn flosun-button secondary-btn theme-color rounded-0">Register</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Register Area End Here -->

{% endblock %}