florapp/config/urls.py
from cgitb import handler
from django.contrib import admin
from django.urls import path, include
from orders import views
from users import views as users_views

urlpatterns = [
    path('', views.load_index, name='index'),
    path('about-us/', views.load_aboutus, name='about_us'),
    path('blog/', views.load_blog, name='blog'),
    path('cart/', views.load_cart, name='cart'),
    path('checkout/', views.load_checkout, name='checkout'),
    path('compare/', views.load_compare, name='compare'),
    path('contact-us/', views.load_contactus, name='contact_us'),
    path('error-404/', views.load_error_404, name='error-404'),
    path('FAQ/', views.load_faq, name='faq'),
    path('login/', users_views.LoginView.as_view(), name='login'),
    path("logout/",users_views.LogoutView.as_view(), name="logout"),
    path('my_account/', views.load_myaccount, name='my_account'),
    path('register/', users_views.SignUpView.as_view(), name='register'),
    path("shop/",views.load_shop, name="shop"),
    path('whislist/', views.load_whislist, name='whislist'),
    path('admin/', admin.site.urls),
    path('orders/', include("orders.urls")),
    path('users/', include("users.urls"))

]

handler404 = "orders.views.load_error_404"

florapp/users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    
]

florapp/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator

class User(AbstractUser):
    """
    Extend from django's abstract User, change the username field
    to email field
    """

    email = models.EmailField(
        'email address',
        unique=True,
        error_messages={
            'unique':'Ya existe un usuario con ese email'
        }
    )

    phone_regex = RegexValidator(
        regex = r'\+?1?\d{9,15}$',
        message="El numero de telefono debe ser ingresado en el formato: +529999999"
    )

    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)

    

florapp/users/forms.py
import re
from django import forms
from users.models import User

class SignUpForm(forms.Form):

    first_name = forms.CharField(min_length= 2, max_length=15)
    last_name = forms.CharField(min_length= 2, max_length=15)
    username = forms.CharField(min_length= 4, max_length=15)
    email = forms.CharField(min_length=6,max_length=50,widget = forms.EmailInput())
    password = forms.CharField(max_length=70 , widget=forms.PasswordInput())
    password_confirmation = forms.CharField(max_length=70 , widget=forms.PasswordInput())

    def clean_username(self):
        """Username must be unique"""

        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('El username ya existe')
        pattern = "^[A-Za-z0-9_]*$"
        valid = bool(re.match(pattern, username))
        if not valid:
            raise forms.ValidationError("El username solo puede contener letras A-z, numeros 0-9 y _")
        return username

    def clean_email(self):
        """email must be unique"""

        email = self.cleaned_data['email']
        email_taken = User.objects.filter(email=email).exists()
        if email_taken:
            raise forms.ValidationError('El email ya esta registrado')
        return email

    def clean(self):
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Las contraseñas no coinciden')

        return data

    def save(self):
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        user.save()

florapp/users/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic  import FormView

from users.forms import SignUpForm

class LoginView(LoginView):
    template_name = 'orders/login.html'

class LogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'logout.html'

class SignUpView(FormView):
    form_class = SignUpForm
    success_url = reverse_lazy('login')
    template_name = 'orders/register.html'

    def form_valid(self, form):
        "Safe form data"
        form.save()
        return super().form_valid(form)

florapp/users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'orders/reset.css' %}">
    <link rel="stylesheet" href="{% static 'orders/styles.css' %}">
    {% block head_content %}{% endblock %}
</head>
<body>
    {% block container %}{% endblock%}

    <footer>
        {% comment %} <a href="#">Contacto 1</a>
        <a href="#">Contacto 2</a>
        <a href="#">Términos y condiciones</a> {% endcomment %}
    </footer>
</body>
</html>

florapp/users/templates/users/login.html
{% extends "users/base.html"%}
{% load static %}

{% block head_content %}
<title> Ingresar </title>
{% endblock %}

{% block container %}
    
    <header><h1>Ingresa</h1></header>

    {% if form.errors %}

        <p style="color:red"><strong>{{form.non_field_errors}}</strong></p>
        <br>
            
    {%endif%}

    <link rel="stylesheet" href="{% static 'orders/new.css' %}">
    <form method="POST" action="{% url 'users:login' %}">
        
        {% csrf_token %}
        
        
        <input type="text" class="input_text" placeholder="username" name="username" />
        
        <input type="password" class="input_text" placeholder="Password" name="password" />
        
        <input type="submit" class="input_submit" value="Ingresar"> 

    </form>
    <br>
    <p>No tienes un usuario?<a href="{% url 'users:signup' %}"> Registrate aquí</a></p>

{% endblock%}

florapp/users/templates/users/signup.html
{% extends "users/base.html"%}
{% load static %}

{% block head_content %}
<title>Sing up</title>
{% endblock %}

{% block container %}

    <header><h1>Registrate</h1></header>

    {% if form.errors %}
        <p style="color:red"><strong> {{ form.non_field_errors }}</strong></p>
        <br>
    {% endif %}

    <link rel="stylesheet" href="{% static 'users/signup.css' %}">
    <form method= "POST" action="{% url 'users:signup'%}">

        {% csrf_token %}


        <input type="text" class="input_text" name="username" maxlength="15" minlength="4" placeholder="Username" required="" id="id_username"><br>
        {{form.errors.username}}
        <input type="email" class="input_text" name="email" maxlength="50" minlength="6" placeholder="Email" required="" id="id_email"><br>
        {{form.errors.email}}
        <input type="password" class="input_text" name="password" maxlength="70" placeholder="Password" required="" id="id_password"><br>
        {{form.errors.password}}
        <input type="password" class="input_text" name="password_confirmation" maxlength="70" placeholder="Password confirmation" required="" id="id_password_confirmation"><br><br> 
        {{form.errors.password_confirmation}}
        <input type="submit" class="input_submit" value="Registrarme!">

    </form>
    <br><br>

    <p><a href="{% url 'users:login' %}">ya tienes cuenta? Ingresa aquí</a></p>
    
{% endblock%}