florapp/config/urls.py
from cgitb import handler
from django.contrib import admin
from django.urls import path, include
from orders import views
from users import views as users_views

urlpatterns = [
    path('', views.load_index, name='index'),
    path('about-us/', views.load_aboutus, name='about_us'),
    path('blog/', views.load_blog, name='blog'),
    path('cart/', views.load_cart, name='cart'),
    path('checkout/', views.load_checkout, name='checkout'),
    path('compare/', views.load_compare, name='compare'),
    path('contact-us/', views.load_contactus, name='contact_us'),
    path('error-404/', views.load_error_404, name='error-404'),
    path('FAQ/', views.load_faq, name='faq'),
    path('login/', users_views.LoginView.as_view(), name='login'),
    path("logout/",users_views.LogoutView.as_view(), name="logout"),
    path('my_account/', views.load_myaccount, name='my_account'),
    path('register/', users_views.SignUpView.as_view(), name='register'),
    path("shop/",views.load_shop, name="shop"),
    path('whislist/', views.load_whislist, name='whislist'),
    path('admin/', admin.site.urls),
    path('orders/', include("orders.urls")),
    path('users/', include("users.urls"))

]

handler404 = "orders.views.load_error_404"

florapp/orders/urls.py
from django.urls import path

from . import views

app_name = "orders"
urlpatterns = [
    path("",views.IndexView.as_view(), name="index"),
    path("status/<str:status>/",views.IndexView.as_view(), name="index"),
    path("<int:pk>/",views.DetailView.as_view(), name="detail"),
    path("new/",views.CreateOrderView.as_view(), name="new"),
    path("prueba/",views.prueba, name="prueba"),
    path("product/",views.load_product, name="product")
]

florapp/users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    
]

florapp/orders/models.py
from django.db import models
from users.models import User

class Flower(models.Model):

    name = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    unit_price = models.FloatField()

    def __str__(self):
        return self.name

class Order(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    flower = models.ForeignKey(Flower,on_delete=models.PROTECT)
    units = models.IntegerField(default=0)
    observations_text = models.CharField(max_length=500)
    status = models.CharField(max_length=30, choices=[('Activo','Activo'),('Cancelado','Cancelado'),('Despachado','Despachado'),('Entregado','Entregado')], default='Activo')
    pub_date = models.DateTimeField("date published",auto_now_add=True)

    def __str__(self):
        return 'Orden ' + str(self.pk)

florapp/orders/forms.py
# django
from django import forms

# models

from orders.models import Flower, Order

class OrderForm(forms.ModelForm):
    """Order model form"""

    class Meta:
        """Form settings"""

        model = Order
        fields = ['user','flower','units', 'observations_text']

    flower = forms.ModelChoiceField(
        queryset = Flower.objects.all(), 
        empty_label = None,
    )

florapp/orders/views.py
from multiprocessing import context
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy
from orders.models import Order
from orders.forms import OrderForm
from django.shortcuts import render



class IndexView(LoginRequiredMixin,generic.ListView):
    template_name = "orders/index2.html"
    context_object_name = "context"

    def get_queryset(self):
        """Return the last  published orders"""
        user = self.request.user
        context = {}
        context['latest_orders_list'] = Order.objects.filter(user=user)
        if 'status' in self.kwargs:
            status = self.kwargs['status']
            context[f'{status}'] = status
            context['latest_orders_list'] =Order.objects.filter(user=user).filter(status=status)
            return context
        context['todas'] = 'todas'
        return context

class DetailView(LoginRequiredMixin,generic.DetailView):
    model = Order
    template_name = "orders/detail.html"

    def get_queryset(self):
        user = self.request.user 
        return Order.objects.filter(user=user)

class CreateOrderView(LoginRequiredMixin, generic.CreateView):
    """Create new Order"""

    form_class = OrderForm
    success_url = reverse_lazy('orders:index')
    template_name = 'orders/new.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context

def load_index(request):
    return render(request,"orders/index.html")

def load_aboutus(request):
    return render(request,"orders/about-us.html")

def load_blog(request):
    return render(request,"orders/blog.html")

def load_cart(request):
    return render(request,"orders/cart.html")

def load_checkout(request):
    return render(request,"orders/checkout.html")

def load_compare(request):
    return render(request,"orders/compare.html")

def load_contactus(request):
    return render(request,"orders/contact-us.html")

def load_error_404(request, exception):
    return render(request,"orders/error-404.html",status=404)

def load_faq(request):
    return render(request,"orders/frequently-questions.html")

def load_login(request):
    return render(request,"orders/login.html")

def load_myaccount(request):
    return render(request,"orders/my-account.html")

def load_register(request):
    return render(request,"orders/register.html")

def load_shop(request):
    return render(request,"orders/shop.html")

def load_whislist(request):
    return render(request,"orders/error-404.html")

def load_product(request):
    return render(request,"orders/product-details.html")


def prueba(request):
    return render(request,"orders/prueba.html")

def prueba2(request):
    return render(request,"orders/prueba2.html")

florapp/orders/templates/orders/old/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'orders/reset.css' %}">
    <link rel="stylesheet" href="{% static 'orders/styles.css' %}">
    {% block head_content %}{% endblock %}
</head>
<body>
    {% include "orders/nav.html" %}
    {% comment %} {% include "orders/nav.html" %} {% endcomment %}

    
    {% block container %}{% endblock%}

    <footer>
        {% comment %} <a href="#">Contacto 1</a>
        <a href="#">Contacto 2</a>
        <a href="#">Términos y condiciones</a> {% endcomment %}
    </footer>
</body>
</html>

florapp/orders/templates/orders/old/detail_primera_app.html
{% extends 'orders/base.html' %}
{% load static %}

{% block head_content %}
<title>Orden {{order.id}}</title>
{% endblock %}

{% block container %}
    <link rel="stylesheet" href="{% static 'orders/detail.css' %}">
  
    <header><h1> Orden #{{order.id}}</h1></header>

    {% if error_message %}
        <p><strong> {{ error_message }}</strong></p>
    {% endif %}
    <main>
        <fieldset class="detail">
            <p>Unidades: {{ order.units}}</p>
            <p>Flor: {{ order.flower.name}}</p>
            <p>Fecha de solicitud: {{ order.pub_date}}</p>
            <p>Observaciones:   {{ order.observations_text}} </p>
            <p>Estado:  {{ order.status}} </p>
            
        </fieldset>
        

    </main>
    
{% endblock%}

florapp/orders/templates/orders/old/indexprimeraapp.html
{% extends 'orders/base.html' %}
{% load static %}

{% block head_content %}
<title>Listado de Ordenes</title>
{% endblock %}

{% block container %}
    <link rel="stylesheet" href="{% static 'orders/index.css' %}">
    <header><h1>Listado de Ordenes</h1></header>
    <nav class="nav_menu">
        <ul>
            <li>
                <a class="{{ context.todas }}" href="{% url 'orders:index' %}">Todas</a>
            </li>
            <li>
                <a class="{{ context.Activo }}" href="{% url 'orders:index' 'Activo' %}"> Activas</a>
            </li>
            <li>
                <a class="{{ context.Cancelado }}" href="{% url 'orders:index' 'Cancelado' %}">Canceladas</a>
            </li>
            <li>
                {% comment %} <a class="{{ context.Despachado }}" href="{% url 'orders:index' 'Despachado' %}">Despachadas</a> {% endcomment %}
            </li>
            <li>
                <a class="{{ context.Entregado }}" href="{% url 'orders:index' 'Entregado' %}">Entregadas</a>
            </li>
            
        </ul>
    </nav>
    <main>
        
        {% if context.latest_orders_list %}
        
            <ul class="ul_index">
            {% for order in context.latest_orders_list  %}
                <fieldset>
                    <li class="li_index">
                        <a href="{% url 'orders:detail' order.id %}">
                            Orden #{{ order.id }}<br>
                            <p>{{order.units}} unidades de {{order.flower.name}}</p>
                        </a>
                    </li>
                </fieldset>
            {% endfor %}
            </ul>
         
        {% else %}
            <p>No orders are available.</p>
        {% endif %}
    </main>
    
{% endblock%}

florapp/orders/templates/orders/old/nav.html
{% load static %}
<link rel="stylesheet" href="{% static 'orders/nav.css' %}">
<div class="nav">
  <input id="menu__toggle" type="checkbox" />
  <label class="menu__btn" for="menu__toggle">
    <span></span>
  </label>

  <ul class="menu__box">
    <li><a class="menu__item" href="{% url 'orders:index' %}">Dashboard</a></li>
    <li><a class="menu__item" href="{% url 'orders:new' %}">Realizar pedido</a></li>
    <li><a class="menu__item" href="{% url 'users:logout' %}">Logout</a></li>
    {% comment %} <li><a class="menu__item" href="#">Contact</a></li>
    <li><a class="menu__item" href="#">Twitter</a></li> {% endcomment %}
  </ul>
</div>

florapp/orders/templates/orders/old/new.html
{% extends 'orders/base.html' %}
{% load static %}

{% block head_content %}
<title>Nueva orden</title>
{% endblock %}

{% block container %}

        
    <header><h1> Nueva Orden </h1></header>

    {% if error_message %}
        <p><strong> {{ error_message }}</strong></p>
    {% endif %}
    <link rel="stylesheet" href="{% static 'orders/new.css' %}">
    <main>
       <form method="POST" enctype="multipart/form-data">

            {% csrf_token %}
            <input type="hidden" name="user" value="{{ user.pk }}" />

            {# Flower #}
            <select name="flower" class="input_select">
            {% for option in form.flower %}
                {{option}}
            {% endfor  %}
            </select>

            {# Units #}
            <input type="text" class="input_text" name="units" placeholder="Unidades">

            {# observation_text field #}
            <input type="text" class="input_text" name="observations_text" placeholder="Observaciones">
            
            <input type="submit" class="input_submit" value="Aceptar"> 
        </form> 
    </main>
    
{% endblock%}